/*******************************************************************************
 * Copyright (c) 2010 - 2012 ACIN, Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann, Alois Zoitl, Ingo Hegny
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
#include "stringlist.h"

extern const CStringDictionary::TStringId g_nStringIdANALOGICAL_CLOSE_COMFIRM_1 = 0;
extern const CStringDictionary::TStringId g_nStringIdANALOGICAL_OPEN_COMFIRM = 27;
extern const CStringDictionary::TStringId g_nStringIdANY = 51;
extern const CStringDictionary::TStringId g_nStringIdANY_ADAPTER = 55;
extern const CStringDictionary::TStringId g_nStringIdANY_BIT = 67;
extern const CStringDictionary::TStringId g_nStringIdANY_ELEMENTARY = 75;
extern const CStringDictionary::TStringId g_nStringIdANY_INT = 90;
extern const CStringDictionary::TStringId g_nStringIdANY_MAGNITUDE = 98;
extern const CStringDictionary::TStringId g_nStringIdANY_NUM = 112;
extern const CStringDictionary::TStringId g_nStringIdANY_REAL = 120;
extern const CStringDictionary::TStringId g_nStringIdANY_STRING = 129;
extern const CStringDictionary::TStringId g_nStringIdARRAY = 140;
extern const CStringDictionary::TStringId g_nStringIdARTimeOut = 146;
extern const CStringDictionary::TStringId g_nStringIdATimeOut = 156;
extern const CStringDictionary::TStringId g_nStringIdBOOL = 165;
extern const CStringDictionary::TStringId g_nStringIdBYTE = 170;
extern const CStringDictionary::TStringId g_nStringIdCD = 175;
extern const CStringDictionary::TStringId g_nStringIdCDO = 178;
extern const CStringDictionary::TStringId g_nStringIdCLK = 182;
extern const CStringDictionary::TStringId g_nStringIdCMD_DOWN_COMFIRM = 186;
extern const CStringDictionary::TStringId g_nStringIdCMD_UP_COMFIRM = 203;
extern const CStringDictionary::TStringId g_nStringIdCNF = 218;
extern const CStringDictionary::TStringId g_nStringIdCNF_GL_STATUS = 222;
extern const CStringDictionary::TStringId g_nStringIdCNF_MSG = 236;
extern const CStringDictionary::TStringId g_nStringIdCNF_SET_GL_STATUS_LIGHT = 244;
extern const CStringDictionary::TStringId g_nStringIdCNF_SET_STATUS = 268;
extern const CStringDictionary::TStringId g_nStringIdCNF_STATUS_COMFIRM = 283;
extern const CStringDictionary::TStringId g_nStringIdCO = 302;
extern const CStringDictionary::TStringId g_nStringIdCOLD = 305;
extern const CStringDictionary::TStringId g_nStringIdCTR = 310;
extern const CStringDictionary::TStringId g_nStringIdCU = 314;
extern const CStringDictionary::TStringId g_nStringIdCUO = 317;
extern const CStringDictionary::TStringId g_nStringIdCV = 321;
extern const CStringDictionary::TStringId g_nStringIdCYCLE = 324;
extern const CStringDictionary::TStringId g_nStringIdD = 330;
extern const CStringDictionary::TStringId g_nStringIdDATE = 332;
extern const CStringDictionary::TStringId g_nStringIdDATE_AND_TIME = 337;
extern const CStringDictionary::TStringId g_nStringIdDEV_MGR = 351;
extern const CStringDictionary::TStringId g_nStringIdDINT = 359;
extern const CStringDictionary::TStringId g_nStringIdDLY = 364;
extern const CStringDictionary::TStringId g_nStringIdDOOR_CLOSE_COMFIRM = 368;
extern const CStringDictionary::TStringId g_nStringIdDOOR_OPEN_COMFIRM = 387;
extern const CStringDictionary::TStringId g_nStringIdDST = 405;
extern const CStringDictionary::TStringId g_nStringIdDT = 409;
extern const CStringDictionary::TStringId g_nStringIdDWORD = 412;
extern const CStringDictionary::TStringId g_nStringIdDectect_Set_Switch = 418;
extern const CStringDictionary::TStringId g_nStringIdEI = 437;
extern const CStringDictionary::TStringId g_nStringIdEI0 = 440;
extern const CStringDictionary::TStringId g_nStringIdEI1 = 444;
extern const CStringDictionary::TStringId g_nStringIdEI2 = 448;
extern const CStringDictionary::TStringId g_nStringIdEMB_RES = 452;
extern const CStringDictionary::TStringId g_nStringIdEO = 460;
extern const CStringDictionary::TStringId g_nStringIdEO0 = 463;
extern const CStringDictionary::TStringId g_nStringIdEO1 = 467;
extern const CStringDictionary::TStringId g_nStringIdEO2 = 471;
extern const CStringDictionary::TStringId g_nStringIdEO3 = 475;
extern const CStringDictionary::TStringId g_nStringIdERROR = 479;
extern const CStringDictionary::TStringId g_nStringIdE_CTD = 485;
extern const CStringDictionary::TStringId g_nStringIdE_CTU = 491;
extern const CStringDictionary::TStringId g_nStringIdE_CTUD = 497;
extern const CStringDictionary::TStringId g_nStringIdE_CYCLE = 504;
extern const CStringDictionary::TStringId g_nStringIdE_DELAY = 512;
extern const CStringDictionary::TStringId g_nStringIdE_DEMUX = 520;
extern const CStringDictionary::TStringId g_nStringIdE_D_FF = 528;
extern const CStringDictionary::TStringId g_nStringIdE_F_TRIG = 535;
extern const CStringDictionary::TStringId g_nStringIdE_MERGE = 544;
extern const CStringDictionary::TStringId g_nStringIdE_PERMIT = 552;
extern const CStringDictionary::TStringId g_nStringIdE_RDELAY = 561;
extern const CStringDictionary::TStringId g_nStringIdE_REND = 570;
extern const CStringDictionary::TStringId g_nStringIdE_RESTART = 577;
extern const CStringDictionary::TStringId g_nStringIdE_RS = 587;
extern const CStringDictionary::TStringId g_nStringIdE_RTimeOut = 592;
extern const CStringDictionary::TStringId g_nStringIdE_R_TRIG = 603;
extern const CStringDictionary::TStringId g_nStringIdE_SELECT = 612;
extern const CStringDictionary::TStringId g_nStringIdE_SPLIT = 621;
extern const CStringDictionary::TStringId g_nStringIdE_SR = 629;
extern const CStringDictionary::TStringId g_nStringIdE_SWITCH = 634;
extern const CStringDictionary::TStringId g_nStringIdE_TRAIN = 643;
extern const CStringDictionary::TStringId g_nStringIdE_T_FF = 651;
extern const CStringDictionary::TStringId g_nStringIdE_TimeOut = 658;
extern const CStringDictionary::TStringId g_nStringIdG = 668;
extern const CStringDictionary::TStringId g_nStringIdGATE = 670;
extern const CStringDictionary::TStringId g_nStringIdGEN_CLIENT = 675;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_DEMUX = 686;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_MUX = 698;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBL = 708;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBLISH = 717;
extern const CStringDictionary::TStringId g_nStringIdGEN_SERVER = 729;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBL = 740;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBSCRIBE = 749;
extern const CStringDictionary::TStringId g_nStringIdGET_GL_STATUS = 763;
extern const CStringDictionary::TStringId g_nStringIdID = 777;
extern const CStringDictionary::TStringId g_nStringIdIND = 780;
extern const CStringDictionary::TStringId g_nStringIdINIT = 784;
extern const CStringDictionary::TStringId g_nStringIdINITO = 789;
extern const CStringDictionary::TStringId g_nStringIdINT = 795;
extern const CStringDictionary::TStringId g_nStringIdK = 799;
extern const CStringDictionary::TStringId g_nStringIdLD = 801;
extern const CStringDictionary::TStringId g_nStringIdLDO = 804;
extern const CStringDictionary::TStringId g_nStringIdLGCS_MAIN_CONTROLLER = 808;
extern const CStringDictionary::TStringId g_nStringIdLINT = 829;
extern const CStringDictionary::TStringId g_nStringIdLREAL = 834;
extern const CStringDictionary::TStringId g_nStringIdLWORD = 840;
extern const CStringDictionary::TStringId g_nStringIdMGR = 846;
extern const CStringDictionary::TStringId g_nStringIdMGR_FF = 850;
extern const CStringDictionary::TStringId g_nStringIdMGR_ID = 857;
extern const CStringDictionary::TStringId g_nStringIdN = 864;
extern const CStringDictionary::TStringId g_nStringIdPARAMS = 866;
extern const CStringDictionary::TStringId g_nStringIdPERMIT = 873;
extern const CStringDictionary::TStringId g_nStringIdPV = 880;
extern const CStringDictionary::TStringId g_nStringIdQ = 883;
extern const CStringDictionary::TStringId g_nStringIdQD = 885;
extern const CStringDictionary::TStringId g_nStringIdQI = 888;
extern const CStringDictionary::TStringId g_nStringIdQO = 891;
extern const CStringDictionary::TStringId g_nStringIdQU = 894;
extern const CStringDictionary::TStringId g_nStringIdR = 897;
extern const CStringDictionary::TStringId g_nStringIdREAD = 899;
extern const CStringDictionary::TStringId g_nStringIdREAD_GL_STATUS = 904;
extern const CStringDictionary::TStringId g_nStringIdREAL = 919;
extern const CStringDictionary::TStringId g_nStringIdREQ = 924;
extern const CStringDictionary::TStringId g_nStringIdRESP = 928;
extern const CStringDictionary::TStringId g_nStringIdRMT_RES = 933;
extern const CStringDictionary::TStringId g_nStringIdRO = 941;
extern const CStringDictionary::TStringId g_nStringIdRQST = 944;
extern const CStringDictionary::TStringId g_nStringIdRSP = 949;
extern const CStringDictionary::TStringId g_nStringIdS = 953;
extern const CStringDictionary::TStringId g_nStringIdSINT = 955;
extern const CStringDictionary::TStringId g_nStringIdSTART = 960;
extern const CStringDictionary::TStringId g_nStringIdSTATUS = 966;
extern const CStringDictionary::TStringId g_nStringIdSTOP = 973;
extern const CStringDictionary::TStringId g_nStringIdSTRING = 978;
extern const CStringDictionary::TStringId g_nStringIdSWITCHsim = 985;
extern const CStringDictionary::TStringId g_nStringIdSwitch_Down_confirm = 995;
extern const CStringDictionary::TStringId g_nStringIdSwitch_Up_confirm = 1015;
extern const CStringDictionary::TStringId g_nStringIdTI = 1033;
extern const CStringDictionary::TStringId g_nStringIdTIME = 1036;
extern const CStringDictionary::TStringId g_nStringIdTIME_OF_DAY = 1041;
extern const CStringDictionary::TStringId g_nStringIdTimeOut = 1053;
extern const CStringDictionary::TStringId g_nStringIdTimeOutSocket = 1061;
extern const CStringDictionary::TStringId g_nStringIdUDINT = 1075;
extern const CStringDictionary::TStringId g_nStringIdUINT = 1081;
extern const CStringDictionary::TStringId g_nStringIdULINT = 1086;
extern const CStringDictionary::TStringId g_nStringIdUSINT = 1092;
extern const CStringDictionary::TStringId g_nStringIdWARM = 1098;
extern const CStringDictionary::TStringId g_nStringIdWORD = 1103;
extern const CStringDictionary::TStringId g_nStringIdWSTRING = 1108;
extern const CStringDictionary::TStringId g_nStringIdaddress = 1116;
extern const CStringDictionary::TStringId g_nStringIderror_code = 1124;
extern const CStringDictionary::TStringId g_nStringIdgear_lever_msg = 1135;
extern const CStringDictionary::TStringId g_nStringIdgear_lever_status = 1150;
extern const CStringDictionary::TStringId g_nStringIdin = 1168;
extern const CStringDictionary::TStringId g_nStringIdip_address = 1171;
extern const CStringDictionary::TStringId g_nStringIdparams = 1182;
extern const CStringDictionary::TStringId g_nStringIdport = 1189;
extern const CStringDictionary::TStringId g_nStringIdset_alarm_time = 1194;
extern const CStringDictionary::TStringId g_nStringIdset_gear_lever_status = 1209;
extern const CStringDictionary::TStringId g_nStringIdstatus = 1231;
extern const CStringDictionary::TStringId g_nStringIdwARM = 1238;
extern const CStringDictionary::TStringId g_nStringIdNextFreeId = 1243;
extern const unsigned int cg_nNumOfConstStrings = 158;


#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  CStringDictionary::TStringId CStringDictionary::scm_aunIdList[cg_unFORTE_StringDictInitialMaxNrOfStrings]
#else
  const CStringDictionary::TStringId CStringDictionary::scm_aunIdList[] 
#endif
  = {0, 27, 51, 55, 67, 75, 90, 98, 112, 120, 129, 140, 146, 156, 165, 170, 175, 178, 182, 186, 203, 218, 222, 236, 244, 268, 283, 302, 305, 310, 314, 317, 321, 324, 330, 332, 337, 351, 359, 364, 368, 387, 405, 409, 412, 418, 437, 440, 444, 448, 452, 460, 463, 467, 471, 475, 479, 485, 491, 497, 504, 512, 520, 528, 535, 544, 552, 561, 570, 577, 587, 592, 603, 612, 621, 629, 634, 643, 651, 658, 668, 670, 675, 686, 698, 708, 717, 729, 740, 749, 763, 777, 780, 784, 789, 795, 799, 801, 804, 808, 829, 834, 840, 846, 850, 857, 864, 866, 873, 880, 883, 885, 888, 891, 894, 897, 899, 904, 919, 924, 928, 933, 941, 944, 949, 953, 955, 960, 966, 973, 978, 985, 995, 1015, 1033, 1036, 1041, 1053, 1061, 1075, 1081, 1086, 1092, 1098, 1103, 1108, 1116, 1124, 1135, 1150, 1168, 1171, 1182, 1189, 1194, 1209, 1231, 1238};

#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  char CStringDictionary::scm_acConstStringBuf[cg_unFORTE_StringDictInitialStringBufSize]
#else
  const char CStringDictionary::scm_acConstStringBuf[] 
#endif
  = {"ANALOGICAL_CLOSE_COMFIRM_1\0ANALOGICAL_OPEN_COMFIRM\0ANY\0ANY_ADAPTER\0ANY_BIT\0ANY_ELEMENTARY\0ANY_INT\0ANY_MAGNITUDE\0ANY_NUM\0ANY_REAL\0ANY_STRING\0ARRAY\0ARTimeOut\0ATimeOut\0BOOL\0BYTE\0CD\0CDO\0CLK\0CMD_DOWN_COMFIRM\0CMD_UP_COMFIRM\0CNF\0CNF_GL_STATUS\0CNF_MSG\0CNF_SET_GL_STATUS_LIGHT\0CNF_SET_STATUS\0CNF_STATUS_COMFIRM\0CO\0COLD\0CTR\0CU\0CUO\0CV\0CYCLE\0D\0DATE\0DATE_AND_TIME\0DEV_MGR\0DINT\0DLY\0DOOR_CLOSE_COMFIRM\0DOOR_OPEN_COMFIRM\0DST\0DT\0DWORD\0Dectect_Set_Switch\0EI\0EI0\0EI1\0EI2\0EMB_RES\0EO\0EO0\0EO1\0EO2\0EO3\0ERROR\0E_CTD\0E_CTU\0E_CTUD\0E_CYCLE\0E_DELAY\0E_DEMUX\0E_D_FF\0E_F_TRIG\0E_MERGE\0E_PERMIT\0E_RDELAY\0E_REND\0E_RESTART\0E_RS\0E_RTimeOut\0E_R_TRIG\0E_SELECT\0E_SPLIT\0E_SR\0E_SWITCH\0E_TRAIN\0E_T_FF\0E_TimeOut\0G\0GATE\0GEN_CLIENT\0GEN_E_DEMUX\0GEN_E_MUX\0GEN_PUBL\0GEN_PUBLISH\0GEN_SERVER\0GEN_SUBL\0GEN_SUBSCRIBE\0GET_GL_STATUS\0ID\0IND\0INIT\0INITO\0INT\0K\0LD\0LDO\0LGCS_MAIN_CONTROLLER\0LINT\0LREAL\0LWORD\0MGR\0MGR_FF\0MGR_ID\0N\0PARAMS\0PERMIT\0PV\0Q\0QD\0QI\0QO\0QU\0R\0READ\0READ_GL_STATUS\0REAL\0REQ\0RESP\0RMT_RES\0RO\0RQST\0RSP\0S\0SINT\0START\0STATUS\0STOP\0STRING\0SWITCHsim\0Switch_Down_confirm\0Switch_Up_confirm\0TI\0TIME\0TIME_OF_DAY\0TimeOut\0TimeOutSocket\0UDINT\0UINT\0ULINT\0USINT\0WARM\0WORD\0WSTRING\0address\0error_code\0gear_lever_msg\0gear_lever_status\0in\0ip_address\0params\0port\0set_alarm_time\0set_gear_lever_status\0status\0wARM\0"};

 
