/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCNF_SET_STATUS;
 extern const CStringDictionary::TStringId g_nStringIdDectect_Set_Switch;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdLINT;
 extern const CStringDictionary::TStringId g_nStringIdPARAMS;
 extern const CStringDictionary::TStringId g_nStringIdREAD_GL_STATUS;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTI;
 extern const CStringDictionary::TStringId g_nStringIdin;
 extern const CStringDictionary::TStringId g_nStringIdip_address;
 extern const CStringDictionary::TStringId g_nStringIdport;
 extern const CStringDictionary::TStringId g_nStringIdset_alarm_time;

