/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdDisplay_Interface;
 extern const CStringDictionary::TStringId g_nStringIdLINT;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSHOH_MAG_light;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_DOWN;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_SET_STATUS;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_UP_;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTI;
 extern const CStringDictionary::TStringId g_nStringIdgear_lever_status;
 extern const CStringDictionary::TStringId g_nStringIdip_address;
 extern const CStringDictionary::TStringId g_nStringIdmsg_light;
 extern const CStringDictionary::TStringId g_nStringIdport;
 extern const CStringDictionary::TStringId g_nStringIdset_gear_lever_status;

