/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdDown;
 extern const CStringDictionary::TStringId g_nStringIdGearLever;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdONE_TIME_ALARM_RING;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_GEAR_STATUS;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdUP;
 extern const CStringDictionary::TStringId g_nStringIdset_time_alarm;
 extern const CStringDictionary::TStringId g_nStringIdset_time_message;
 extern const CStringDictionary::TStringId g_nStringIdshow_status;
 extern const CStringDictionary::TStringId g_nStringIdshow_time;

