/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdANALOGICAL_CLOSE_COMFIRM_1;
 extern const CStringDictionary::TStringId g_nStringIdANALOGICAL_OPEN_COMFIRM;
 extern const CStringDictionary::TStringId g_nStringIdCMD_DOWN_COMFIRM;
 extern const CStringDictionary::TStringId g_nStringIdCMD_UP_COMFIRM;
 extern const CStringDictionary::TStringId g_nStringIdCNF_GL_STATUS;
 extern const CStringDictionary::TStringId g_nStringIdCNF_MSG;
 extern const CStringDictionary::TStringId g_nStringIdCNF_SET_GL_STATUS_LIGHT;
 extern const CStringDictionary::TStringId g_nStringIdCYCLE;
 extern const CStringDictionary::TStringId g_nStringIdDOOR_CLOSE_COMFIRM;
 extern const CStringDictionary::TStringId g_nStringIdDOOR_OPEN_COMFIRM;
 extern const CStringDictionary::TStringId g_nStringIdERROR;
 extern const CStringDictionary::TStringId g_nStringIdGET_GL_STATUS;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINT;
 extern const CStringDictionary::TStringId g_nStringIdLGCS_MAIN_CONTROLLER;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTI;
 extern const CStringDictionary::TStringId g_nStringIderror_code;
 extern const CStringDictionary::TStringId g_nStringIdgear_lever_msg;
 extern const CStringDictionary::TStringId g_nStringIdgear_lever_status;
 extern const CStringDictionary::TStringId g_nStringIdset_gear_lever_status;
 extern const CStringDictionary::TStringId g_nStringIdstatus;

