/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdBusAdapterOut;
 extern const CStringDictionary::TStringId g_nStringIdBusInitSpeed;
 extern const CStringDictionary::TStringId g_nStringIdBusInterface;
 extern const CStringDictionary::TStringId g_nStringIdBusLoopSpeed;
 extern const CStringDictionary::TStringId g_nStringIdBusSelectPin;
 extern const CStringDictionary::TStringId g_nStringIdEBBusAdapter;
 extern const CStringDictionary::TStringId g_nStringIdEBMaster;
 extern const CStringDictionary::TStringId g_nStringIdIND;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdQI;
 extern const CStringDictionary::TStringId g_nStringIdQO;
 extern const CStringDictionary::TStringId g_nStringIdSTATUS;
 extern const CStringDictionary::TStringId g_nStringIdSlaveUpdateInterval;
 extern const CStringDictionary::TStringId g_nStringIdUDINT;
 extern const CStringDictionary::TStringId g_nStringIdUINT;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;

