/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdBusAdapterIn;
 extern const CStringDictionary::TStringId g_nStringIdBusAdapterOut;
 extern const CStringDictionary::TStringId g_nStringIdEBBusAdapter;
 extern const CStringDictionary::TStringId g_nStringIdEBSlave2301;
 extern const CStringDictionary::TStringId g_nStringIdIND;
 extern const CStringDictionary::TStringId g_nStringIdMAP;
 extern const CStringDictionary::TStringId g_nStringIdMAPO;
 extern const CStringDictionary::TStringId g_nStringIdQI;
 extern const CStringDictionary::TStringId g_nStringIdQO;
 extern const CStringDictionary::TStringId g_nStringIdRelay_1;
 extern const CStringDictionary::TStringId g_nStringIdRelay_2;
 extern const CStringDictionary::TStringId g_nStringIdRelay_3;
 extern const CStringDictionary::TStringId g_nStringIdRelay_4;
 extern const CStringDictionary::TStringId g_nStringIdRelay_5;
 extern const CStringDictionary::TStringId g_nStringIdRelay_6;
 extern const CStringDictionary::TStringId g_nStringIdSTATUS;
 extern const CStringDictionary::TStringId g_nStringIdUINT;
 extern const CStringDictionary::TStringId g_nStringIdUpdateInterval;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;

